### ISSUE TITLE
Support for Laravel 9/10

### ISSUE THREAD

**Issue by DreadfulCode** [artisansdk/cqrs#4]
Are there any plans in the near future to get this working with the latest versions of Laravel? Looking specifically at Laravel 10/Octane.

https://laravel.com/docs/10.x/octane

Thank you.

**Comment by dalabarge** [comment]
Just pushed out an update to fix some PHP 8.2 issues and some typing problems with Laravel 10. Was there something specific about Octane that isn't supported by this package now that Laravel 10 is compatible? Please report any Laravel 10 incompatibilities you find.
