### ISSUE TITLE
Incompatibility with Laravel v10.3.3 and PHP8.2.3

### ISSUE THREAD

**Issue by saiht** [artisansdk/cqrs#5]
Hi, 

Just to note that with a fresh install of Laravel v10.3.3 and PHP 8.2.3, the installation of this package cannot be done.
Here is the error:
- With `composer require artisansdk/cqrs:dev-master`
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/20522466/224220310-d00eaf9f-f0b1-4352-a858-c7f1c8f8156d.png">

- With `composer require artisansdk/cqrs`
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/20522466/224220391-a409fda7-3633-40dd-9dfc-508b115d5c34.png">

**Comment by dalabarge** [comment]
There's no tagged, stable release. Update your `composer.json` to include `"minimum-stability": "dev"`. Then run the install. I'm working to get a stable release. In the mean time I'll tag a `1.0.0-rc1`.

**Comment by saiht** [comment]
I just did it before seeing your comment. Thank you.
