### ISSUE TITLE
Upgrade to laravel 11

### ISSUE THREAD

**Issue by clevercodenl** [artisansdk/cqrs#7]
Thank you so much for this package, it's been working great on my laravel v10 application. When upgrading to laravel 11 (locally) I get errors.

 This is my composer.json(require+require-dev):
**composer.json**
```json
  "require": {
        "php": "^8.2",
        "ext-imagick": "*",
        "ext-json": "*",
        "artisansdk/cqrs": "^1.0@RC",
        "friendsofphp/php-cs-fixer": "^3.8",
        "guzzlehttp/guzzle": "^7.0.1",
        "intervention/image": "^2.7",
        "intervention/validation": "^4.4.1",
        "laravel-notification-channels/telegram": "^5.0",
        "laravel/framework": "^11.0.0",
        "laravel/tinker": "^2.5",
        "league/flysystem-aws-s3-v3": "^3.0",
        "mollie/laravel-mollie": "^2.23",
        "predis/predis": "^2.0",
        "sendgrid/sendgrid": "^8.0",
        "sentry/sdk": "^3.3",
        "sentry/sentry-laravel": "^3.4",
        "tymon/jwt-auth": "2.1.1"
    },
    "require-dev": {
        "ext-pcov": "*",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^8.1",
        "nunomaduro/larastan": "^2.0",
        "pcov/clobber": "^2.0",
        "phpunit/php-code-coverage": "^10.0",
        "phpunit/phpunit": "^10.0",
        "spatie/laravel-ignition": "^2.0"
    },
```

**Error in terminal after running composer update**
![image](https://github.com/artisansdk/cqrs/assets/22428906/f4d41bd9-e0a5-42a1-a94f-1402ae6cf23d)

As I understand from the image above, I can't upgrade to laravel v11 because this package needs dependencies which are only available in versions below laravel v11. Can you confirm that this is the problem and if so, provide information of when the compatible version of this package will be available ?

Thank you !!!

**Comment by dalabarge** [comment]
Try running another composer install/update as I just tagged `1.0.0-rc2` off of `master` to address the missing `| ^11.0` install target. Thanks for pointing it out.

**Comment by clevercodenl** [comment]
I am still getting errors, you can see it below: 
![image](https://github.com/artisansdk/cqrs/assets/22428906/8550ef90-bc74-48a6-9328-6a23fa0a83e2)

I think the error is happening because `artisansdk/cqrs@1.0.0-rc2` uses `artisansdk/contract@dev-master` which uses `illuminate/contracts^10`, but `laravel/framework@v11.0.1` only provides  `illuminate/contracts^11`, which is not compatible with `artisansdk/contract@dev-master`. Below are the changes you should apply to the `composer.json` of `artisansdk/contract` (I tried creating a merge request but I don't have  the rights to do that): 
![Screenshot from 2024-06-20 10-32-20](https://github.com/artisansdk/cqrs/assets/22428906/38d91757-925f-4351-b072-2ee1816e66ca)

**Comment by dalabarge** [comment]
Try again. The `artisansdk/contracts` package also needed a version bump.
